### ISSUE TITLE
make all GeoTrackID error

### ISSUE THREAD

**Issue by chrisdane** [InkblotSoftware/aisutil#1]
Hi
In the last make step on linux, I get the errors
```
/usr/include/dlang/dmd/std/format.d(2243,13): Error: no property _value for type aisutil.geotracks.GeoTrackID
/usr/include/dlang/dmd/std/format.d(1875,20): Error: template instance std.format.formatValueImpl!(Appender!string, GeoTrackID, char) error instantiating
/usr/include/dlang/dmd/std/typecons.d(2838,24):        instantiated from here: formatValue!(Appender!string, GeoTrackID, char)
/usr/include/dlang/dmd/std/typecons.d(2816,17):        instantiated from here: toString!(Appender!string)
src/aisutil/filewriting.d(52,5):        instantiated from here: Nullable!(GeoTrackID)
/usr/include/dlang/dmd/std/format.d(2243,13): Error: no property _value for type aisutil.transits.TransitID
/usr/include/dlang/dmd/std/format.d(1875,20): Error: template instance std.format.formatValueImpl!(Appender!string, TransitID, char) error instantiating
```
and then
```
src/aisutil/transits.d(173,17): Error: template aisutil.transits.toTransitResult.visit!(function (TS_AtRest s) @system => AtRest(), delegate (TS_InTransit s) @system => InTransit(curTid), delegate (TS_CheckEnd s) @system => InTransit(curTid)).visit cannot deduce function from argument types !()(TransitState), candidates are:
/usr/include/dlang/dmd/std/variant.d(2315,10):        visit(VariantType)(VariantType variant)
  with VariantType = TransitState
  must satisfy the following constraint:
       isAlgebraic!VariantType
src/aisutil/transits.d(219,15): Error: template aisutil.transits.nextState.visit!(delegate (TS_AtRest s) @system
```
and finally
```
/usr/bin/dmd failed with exit code 1.
make: *** [Makefile:35: bin/aisutil] Error 2
```
Thanks for any help
Chris

```
uname
5.8.14-arch1-1 x86_64 GNU/Linux
dmd --version
DMD64 D Compiler v2.094.0
dub --version
DUB version 1.23.0, built on Oct  8 2020
```

**Comment by jamtho** [comment]
Hey Chris, so nice to see someone new using this code! What are you working on? I'm interested.

Looks like these bugs stem from DMD changing the 'alias this' semantics, which I think I remember happening over the last few years. Perhaps some tightening up of interfaces too, I'm not sure.

This probably isn't too crazy to fix. I'm working flat out on other things right now, but can happily advise... how's your D?

Or you could always just install a version of DMD from the time of last commit; the 'install' script will do that for you happily.

**Comment by chrisdane** [comment]
Hi jamtho

I dont know if aisutil is what I am looking for. I was hoping to be able to get historic ship data, e.g the lon,lat position records of a specific ship. For example, on https://www.sailwx.info/shiptrack/search.phtml you can insert your ship of interest and generate what they call shipdump: a long list with lon,lat coords of this ship in time. Is aisutil is able to do that?

**Comment by jamtho** [comment]
Ah fine, you're looking for data - aisutil is purely for processing data once you've already obtained it.

MarineTraffic is probably what you want.
